### ISSUE TITLE
Suggestion: CI step fail if any file coverage decrease

### ISSUE THREAD

**Issue by TSMMark** [alexcanessa/typescript-coverage-report#172]
**Is your feature request related to a problem? Please describe.**
While reviewing a PR from a teammate, I'd love to know that their changes are not decreasing Ts coverage on any file

**Describe the solution you'd like**
compare TS coverage per file on current branch vs base branch and report delta

**Describe alternatives you've considered**

**Additional context**
Thank you so much for this package — originally coming over from flow several years ago, I've really missed this feature. Very excited to implement type-coverage checks once again!

**Comment by alexcanessa** [comment]
Partly addressed in #196, and I want to be straight about which part.

**What now works.** The tool emits `lcov.info`, which is what lets Codecov, Coveralls or SonarQube tell you *"this pull request lowered type coverage on `src/foo.ts`"* — per file, against the base branch, as a PR comment:

```yaml
- run: npx typescript-coverage-report --reporters lcov --threshold 90
- uses: codecov/codecov-action@v5
  with:
    files: coverage-ts/lcov.info
```

That is your use case — *"compare TS coverage per file on current branch vs base branch and report delta"* — and it is the flow-coverage-report workflow you said you missed.

**What does not.** There is no native delta. The tool still cannot, on its own, fail a build because one file got worse.

I am leaving this open rather than closing it, because routing you to a third-party service is not the same as implementing what you asked for. But I want to flag a design question before anyone builds it: doing this natively means the tool needs to know about git — checking out or fetching the base branch, running twice, and diffing. That is a lot of machinery to duplicate something Codecov already does well.

A lighter option, which `--history-file` (#74) now makes possible, is comparing against a committed baseline file rather than a branch. That stays git-agnostic. If that would solve your problem, say so and I will scope it that way.

Either way, please try the lcov route first — if it covers you, that is useful to know before building more.

**Comment by alexcanessa** [comment]
**2.0.0 is live** with lcov output, so the CI-side half of this works now:

```yaml
- run: npx typescript-coverage-report --reporters lcov --threshold 90
- uses: codecov/codecov-action@v5
  with:
    files: coverage-ts/lcov.info
```

@TSMMark that gets you per-file deltas against the base branch as a PR comment, which is the flow-coverage-report behaviour you described missing.

Still open because there is no *native* delta — the tool cannot fail a build on its own because one file got worse. Worth trying the above first; if it covers you, that is useful to know before building more.
